site_name: Noruh
nav:
    - Inicio: 'index.md'
    - Panejamento:
        - 'Cronograma': './planejamento/cronograma.md'
        - 'Ferramentas': './planejamento/ferramentas.md'
    - Pré-Rastreabilidade:
        - 'Rich Picture': './pre-rastreabilidade/RichPicture.md'
    - Elicitação: 
        - 'Personas': './elicitacao/personas.md'
        - Técnicas:
            - 'Brainstorm': './elicitacao/tecnicas/brainstorm.md'
            - 'Introspecção': './elicitacao/tecnicas/introspeccao.md'
            - 'Observação': './elicitacao/tecnicas/observacao.md'
            - 'Questionário': './elicitacao/tecnicas/questionario.md'
        - Priorização:
            - 'MoSCoW': './elicitacao/priorizacao/moscow.md'
        - 'Resultados': './elicitacao/resultados.md'
    - Apresentações:
        - 'Apresentação 1': './apresentacoes/apresentacao1.md'
        - 'Apresentação 2': './apresentacoes/apresentacao2.md'
    - Modelagem:
        - 'Especificação Suplementar': './modelagem/especificacao.md'
        - 'Cenários': './modelagem/cenarios.md'
        - 'Léxicos': './modelagem/lexicos.md'
        - 'Casos de Uso': './modelagem/casosDeUso.md'
    
        
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    scheme: slate
