site_name: Noruh
nav:
    - Inicio: 'index.md'
    - Panejamento:
        - 'Cronograma': './planejamento/cronograma.md'
        - 'Ferramentas': './planejamento/ferramentas.md'
    - Pré-Rastreabilidade:
        - 'Rich Picture': './pre-rastreabilidade/RichPicture.md'
    - Apresentações:
        - 'Apresentação 1': './apresentacoes/apresentacao1.md'
        
theme:
  name: material
  palette:
    scheme: slate
